security:
  ignored:
    - "*.bundle.*"

keycloak:
  configurationFile: classpath:keycloak.json
#keycloak:
#  realm: demon
#  auth-server-url: http://127.0.0.1:8090/auth/
#  ssl-required: external
#  resource: k-ui-client
#  public-client: true
#  verify-token-audience: true
#  use-resource-role-mappings: true
#  confidential-port: 0

#spring:
#  security:
#    user:
#      password: password
#  session:
#    store-type: Redis


